name: zenko-zookeeper
home: https://zookeeper.apache.org/
version: 0.0.4
description: Centralized service for maintaining configuration information, naming,
  providing distributed synchronization, and providing group services.
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
sources:
- https://github.com/apache/zookeeper
- https://github.com/kubernetes/contrib/tree/master/statefulset/zookeeper
- https://github.com/Scality/zenko-zookeeper
maintainers:
- name: Scality Zenko Platform Team
  email: zenko-platform@scality.com
